### ISSUE TITLE
3d flip card for video's description

### ISSUE THREAD

**Issue by orizens** [orizens/echoes#23]
flip card for videos/description:

``` css

p::before {
    content: "About";
    display: block;
    font-family: "Open Sans Condensed";
    font-size: 20px;
    margin-top: 5px;
    margin-bottom: 5px;
}

.card .face
{
    -webkit-backface-visibility: hidden;
    backface-visibility: hidden;
    transition: all 1s ease;
}

.card .face.back
{
    -webkit-transform: perspective(400px) rotateY(0deg);
    transform: perspective(400px) rotateY(0deg);
}

.card .front
{
    -webkit-transform: perspective(400px) rotateY(-179.9deg);
    transform: perspective(400px) rotateY(-179.9deg);
}

/*.card:hover .face.back, .card:focus .face.back
{
    -webkit-transform: perspective(400px) rotateY(179.9deg);
    transform: perspective(400px) rotateY(179.9deg);
}

.card:hover .face.front, .card:focus .face.front
{
    -webkit-transform: perspective(400px) rotateY(0deg);
    transform: perspective(400px) rotateY(0deg);
}*/
.show-description .face.back {
    -webkit-transform: perspective(400px) rotateY(179.9deg);
    transform: perspective(400px) rotateY(179.9deg);
}
.show-description .face.front {
    -webkit-transform: perspective(400px) rotateY(0deg);
    transform: perspective(400px) rotateY(0deg);
    -webkit-backface-visibility: visible;
}
```
